# Generated by Django 3.1.3 on 2021-08-10 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210810_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_discount', to='store.book', verbose_name='Книга'),
        ),
    ]
