# Generated by Django 3.1.3 on 2021-08-10 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_discount_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='discount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_discounts', to='store.discount', verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_discounts', to='store.book', verbose_name='Книга'),
        ),
    ]
