# Generated by Django 3.1.3 on 2021-08-11 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210810_0756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='discount',
        ),
    ]
