# Generated by Django 3.1.3 on 2021-08-11 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_book_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='is_active',
            field=models.BooleanField(default=1, verbose_name='Активна'),
            preserve_default=False,
        ),
    ]
